name: Check Lock

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to check'
        required: true
        type: string

jobs:
  check-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Check if environment is locked
        uses: github/lock@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ github.event.inputs.environment }}
          check: true
          continue-on-error: true